### ISSUE TITLE
A space within parentheses causes an error

### ISSUE THREAD

**Issue by duci9y** [runarberg/ascii2mathml#4]
Input: sin x
Output: sin x (Imagine MathML)

Input: sin (x)
Output: sin (x)

Input: sin (x + y)
Error:

```
$ ascii2mathml 'sin (X + Y)'
/usr/local/lib/node_modules/ascii2mathml/lib/syntax.js:84
oupings.open.get(open), str.slice(start + open.length, stop - (close.length - 
                                                                    ^
TypeError: Cannot read property 'length' of undefined
    at Object.splitNextGroup (/usr/local/lib/node_modules/ascii2mathml/lib/syntax.js:84:121)
    at /usr/local/lib/node_modules/ascii2mathml/lib/parser.js:265:56
    at parseone (/usr/local/lib/node_modules/ascii2mathml/lib/parser.js:338:9)
    at parse (/usr/local/lib/node_modules/ascii2mathml/lib/parser.js:140:23)
    at parsegroup (/usr/local/lib/node_modules/ascii2mathml/lib/parser.js:170:18)
    at parseone (/usr/local/lib/node_modules/ascii2mathml/lib/parser.js:250:12)
    at parse (/usr/local/lib/node_modules/ascii2mathml/lib/parser.js:140:23)
    at ascii2mathml (/usr/local/lib/node_modules/ascii2mathml/index.js:63:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/ascii2mathml/bin/index.js:33:24)
    at Module._compile (module.js:460:26)

**Comment by runarberg** [comment]
@duci9y Thanks
